#!/bin/bash

# Copyright (C) 2011, Societe CODDE
# Copyright (C) 2011 Thomas HUMMEL

# Infos
version='CODDE v.2.7'
usage="
Utilisation : codde [-OPTION]...

Permet d'etre rediriger vers le dossier codde-eime et executer 'rvm'

  -d            redirige vers le chemin choisis ex: eime, infra,  rt ... (ex: codde -d infra)
  -s, 		lance bundle exec foreman start -f Procfile.linux (serveur webrick, faye et delayed_job)
  -all, 	lance bundle foreman et rubymine et chrome
  -kill,	kill les process ruby et rubymine
  -r,           restart serveur
  -c, 		lance script/console
  -cd, 		redirige vers le dossier codde-eime et execute 'rvm'
  -fj, 		lance les serveurs faye et delayed job
  -wjf, 	lance les serveurs Webrick, faye et delayed job
  -w, 		lance le serveur Webrick
  -f, 		lance le serveur Faye
  -j, 		lance delayed_job
  -h, --help	liste d'aide

Il est préférable de lancer l'option -s si l'on veut lancer -bg, -f, ou -d
"

# Répertoires
root_rp="$HOME/Apps/"
eime="$root_rp/codde-eime"
rt="$root_rp/request_tracker"
infra="$root_rp/eime-infra"

# Commandes
bundle_foreman="bundle exec foreman start -f Procfile.linux"
livereload="livereload"
webrick="script/server"
rubymine="/opt/RubyMine/bin/rubymine.sh"
chrome="/opt/google/chrome/google-chrome"
faye="$HOME/.rvm/gems/ruby-1.8.7-p358@codde-eime/bin/rackup faye.ru -s thin -E production"
delayed_job="script/delayed_job restart && sleep 999999"
cd="cd $eime && exec $SHELL";

# Messages d'erreurs
CHERROR="CODDE: Erreur: Le chemin est invalide, veuillez indiquer un répertoire valide"
COERROR="CODDE: Erreur: Option introuvable"

check_chemin(){
   chemin="`pwd`";
   if [ "$chemin" != "$eime" ] && [ "$chemin" != "$rt" ]; then
      echo "${CHERROR}";
      exit 1
   fi
}

if test $# = 0; then
	if test -t 0; then
		echo "$usage";
		eval $cd;
		exit 0
	fi
else

	if [ "$1" = "-d" ]; then
		if [ "$2" = "eime" ]; then
			eval "cd $eime && exec $SHELL";
			exit 0
		elif [ "$2" = "rt" ]; then
			eval "cd $rt && exec $SHELL";
			exit 0
		elif [ "$2" = "infra" ]; then
			eval "cd $infra && exec $SHELL";
			exit 0
		else
			echo "Repertoire inconnue";
			exit 0
		fi
	elif [ "$1" = "-s" ]; then
		check_chemin;
		eval "$bundle_foreman" & "$livereload";
		exit 0
	elif [ "$1" = "-all" ]; then
		check_chemin;
		eval "$bundle_foreman" & "$rubymine" & "$chrome" & "$livereload" & gnome-terminal;
		exit 0
	elif [ "$1" = "-r" ]; then
		check_chemin;
		killall ruby;
		sleep 5;
		eval "$bundle_foreman";
		exit 0
	elif [ "$1" = "-kill" ]; then
		check_chemin;
		killall ruby;
		exit 0
	elif [ "$1" = "-w" ]; then
		check_chemin;
		gnome-terminal -e "$webrick";
		exit 0
	elif [ "$1" = "-v" ]; then
		echo "$version";
		exit 0
	elif [ "$1" = "-c" ]; then
		eval "script/console";
		exit 0
	elif [ "$1" = "-j" ]; then
		check_chemin;
		gnome-terminal -e "$delayed_job";
		exit 0
	elif [ "$1" = "-h" ] || [ "$1" = "--help" ] ; then
		echo "$usage";
		exit 0
	elif [ "$2" = "-wdf" ]; then
		check_chemin;
		gnome-terminal --tab -e "$webrick" --tab -e "$delayed_job" --tab -e "$faye";
		exit 0
	elif [ "$1" = "-df" ]; then
		check_chemin;
		gnome-terminal --tab -e "$delayed_job" --tab -e "$faye";
		exit 0
	elif [ "$1" = "-f" ]; then
		check_chemin;
		gnome-terminal -e "$faye";
		exit 0
	elif [ "$1" = "-cd" ]; then
		eval $cd
	else
		echo "$COERROR";
		exit 0
	fi
fi
exit 0;
